version: "3"
services:
    db:
        image: "microsoft/mssql-server-linux"
        environment:
            SA_PASSWORD: "P2ssw0rd@123"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433" 
    web:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - db
    web2:
        build:
            context: .
            dockerfile: DockerfileUPDDB
        depends_on:
            - db
            - web